import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>WSAI</title>
				<meta name="description" content="Generated by JKL & ATW" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>Welcome to WSAI!</h1>

				<Link href="/login">Login</Link>
				<Link href="/register">Register</Link>

				<Link href="/product">Product POC</Link>
			</main>
		</div>
	);
};

export default Home;
